### ISSUE TITLE
Consider an OpenEphys.StarterPack so users only have to download and update one package

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix1-bonsai-docs#31]
So far, this would include Bonsai.StarterPack, OpenEphys.Onix1, and OpenEphys.Commutator.

Not sure where I would put this issue because implementing this suggestion would require its own repo, but this seems like the most relevant repo. The issue lives here in the meanwhile for discussion.

**Comment by jonnew** [comment]
The `Bonsai.StarterPack` should really be called `Bonsai.StandardLibrary`. I think having something with a similar level of generality for `OpenEphys` is not possible. We could ignore this, but I'm not comfortable with that.

Also the StarterPack exists in the core bonsai library so that it is automatically updated any of projects it references is updated. Our version would span multiple repos and so care or automation would be required to keep it up to date.
